version: '2'

services:
    db:
        image: postgres
        environment:
            POSTGRES_DB: symfony
            POSTGRES_USER: symfony
            POSTGRES_PASSWORD: symfony

    php:
        build: ./php-fpm
        expose:
            - "9001"
        volumes:
            - '../:/var/www'
            - '../exercice4/var/log:/var/www/exercice4/var/log'
        links:
            - db

    nginx:
        build: ./nginx
        ports:
            - "80:80"
        links:
            - php
        volumes_from:
            - php
        volumes:
            - '../exercice4/var/log/nginx/:/var/log/nginx'
